
import Project.MyConnection;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yugal
 */
public class PrintPreview extends javax.swing.JFrame {

    /**
     * Creates new form PrintPreview
     */
    public PrintPreview() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public void add(){
        int am1, am2, am3, am4,ans;
        try{
            am1 = Integer.parseInt(amount1.getText());
            am2 = Integer.parseInt(amount2.getText());
            am3 = Integer.parseInt(amount3.getText());
            am4 = Integer.parseInt(amount4.getText());
            ans = am1+am2+am3+am4;
            finalamount.setText(Integer.toString(ans));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void conn(){
      PreparedStatement ps;
       String abc=search.getText();
       String sql;
        sql = "SELECT * FROM `flat` WHERE `flat no.` = "+abc+"";
//        sql = "SELECT * FROM `receipt` WHERE `flat no` = "+abc+"";
             
       try {
            
            
           ps = MyConnection.getConnection().prepareStatement(sql);
           ResultSet rs=ps.executeQuery();  
           if(rs.next()){
               jTextField_sname.setText(rs.getString(1));
               year.setText(rs.getString(2));
               receipt.setText(rs.getString(21));
               name.setText(rs.getString(5));
               floorno.setText(rs.getString(3));
               flatno.setText(rs.getString(4));
               year1.setText(rs.getString(7));
               month.setText(rs.getString(8));
               year2.setText(rs.getString(9));
               month1.setText(rs.getString(6));
               
               
//               amount.setText(rs.getString(11));
               date.setText(rs.getString(18));
               particulars1.setText(rs.getString(10));
               particulars2.setText(rs.getString(11));
               particulars3.setText(rs.getString(12));
               particulars4.setText(rs.getString(13));
               amount1.setText(rs.getString(14));
               amount2.setText(rs.getString(15));
               amount3.setText(rs.getString(16));
               amount4.setText(rs.getString(17));
//               finalamount.setText(rs.getString(12));
               add();
//               textamount.setText(rs.getString(12));
               phoneno.setText(rs.getString(23));
               date1.setText(rs.getString(18));
               mode.setText(rs.getString(19)); 
               trno.setText(rs.getString(20));
              
               
                rs.close();
                ps.close();
                 
           }
           else
           {
                 JOptionPane.showMessageDialog(null,"Flat no. is wrong");
           }
           
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        particulars4 = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        flatno = new javax.swing.JTextField();
        floorno = new javax.swing.JTextField();
        area = new javax.swing.JTextField();
        year1 = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        receipt = new javax.swing.JTextField();
        mode = new javax.swing.JTextField();
        particulars1 = new javax.swing.JTextField();
        particulars2 = new javax.swing.JTextField();
        particulars3 = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        amount1 = new javax.swing.JTextField();
        amount2 = new javax.swing.JTextField();
        amount3 = new javax.swing.JTextField();
        phoneno = new javax.swing.JTextField();
        amount4 = new javax.swing.JTextField();
        finalamount = new javax.swing.JTextField();
        textamount = new javax.swing.JTextField();
        trno = new javax.swing.JTextField();
        date1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_sname = new javax.swing.JTextField();
        month1 = new javax.swing.JTextField();
        year2 = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        particulars4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        particulars4.setText("part4");
        particulars4.setBorder(null);
        jPanel2.add(particulars4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 240, 20));

        year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        year.setText("year");
        year.setBorder(null);
        jPanel2.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 70, 20));

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setText("name");
        name.setBorder(null);
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 240, 20));

        flatno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        flatno.setText("flat no.");
        flatno.setBorder(null);
        jPanel2.add(flatno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 70, 20));

        floorno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        floorno.setText("floor no.");
        floorno.setBorder(null);
        jPanel2.add(floorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 247, 60, 20));

        area.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        area.setText("area");
        area.setBorder(null);
        jPanel2.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 60, 20));

        year1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        year1.setText("fromyear");
        year1.setBorder(null);
        year1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year1ActionPerformed(evt);
            }
        });
        jPanel2.add(year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 50, -1));

        amount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amount.setBorder(null);
        jPanel2.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 100, 20));

        receipt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        receipt.setText("reno");
        receipt.setBorder(null);
        jPanel2.add(receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 70, 20));

        mode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mode.setText("mode");
        mode.setBorder(null);
        jPanel2.add(mode, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 130, 20));

        particulars1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        particulars1.setText("part1");
        particulars1.setBorder(null);
        jPanel2.add(particulars1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 240, 20));

        particulars2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        particulars2.setText("part2");
        particulars2.setBorder(null);
        jPanel2.add(particulars2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 240, 20));

        particulars3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        particulars3.setText("part3");
        particulars3.setBorder(null);
        jPanel2.add(particulars3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 240, -1));

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setText("date");
        date.setBorder(null);
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 110, 20));

        amount1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amount1.setText("amount1");
        amount1.setBorder(null);
        jPanel2.add(amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 70, 20));

        amount2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amount2.setText("am2");
        amount2.setBorder(null);
        jPanel2.add(amount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 70, 20));

        amount3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amount3.setText("am3");
        amount3.setBorder(null);
        amount3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount3ActionPerformed(evt);
            }
        });
        jPanel2.add(amount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 70, -1));

        phoneno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneno.setText("mobileno");
        phoneno.setBorder(null);
        jPanel2.add(phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 200, -1));

        amount4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amount4.setText("am4");
        amount4.setBorder(null);
        jPanel2.add(amount4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 70, -1));

        finalamount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalamount.setBorder(null);
        finalamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalamountActionPerformed(evt);
            }
        });
        jPanel2.add(finalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 70, -1));

        textamount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textamount.setText("text");
        textamount.setBorder(null);
        jPanel2.add(textamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 250, -1));

        trno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        trno.setText("trno");
        trno.setBorder(null);
        jPanel2.add(trno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 80, -1));

        date1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date1.setText("date1");
        date1.setBorder(null);
        jPanel2.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 630, 130, -1));

        jLabel1.setText("to");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 20, 20));

        jLabel3.setText("Sarswat Bank ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, 150, -1));

        jTextField_sname.setText("Society name");
        jPanel2.add(jTextField_sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, -1));

        month1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        month1.setText("frommonth");
        month1.setBorder(null);
        month1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month1ActionPerformed(evt);
            }
        });
        jPanel2.add(month1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 50, -1));

        year2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        year2.setText(" toyear");
        year2.setBorder(null);
        year2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year2ActionPerformed(evt);
            }
        });
        jPanel2.add(year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 50, -1));

        month.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        month.setText("tomonth");
        month.setBorder(null);
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        jPanel2.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 60, -1));

        jLabel5.setText("Chinchwad");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 704, 150, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/E.jpg"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 202, 160, 30));

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-send-to-printer-48.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 5, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sign.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(783, 839));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void year1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PrinterJob job =PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        
        job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                
                if (pageNum>0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.50,0.74);
                
                jPanel2.paint(g2);
                return Printable.PAGE_EXISTS;
            }
        });
        boolean ok = job.printDialog();
        if(ok){
            try{
                job.print();
            }
            catch (PrinterException ex){
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void amount3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount3ActionPerformed

    private void finalamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalamountActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_finalamountActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        conn();
    }//GEN-LAST:event_searchActionPerformed

    private void month1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_month1ActionPerformed

    private void year2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year2ActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintPreview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintPreview().setVisible(true);
            }
        });
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JTextField amount1;
    private javax.swing.JTextField amount2;
    private javax.swing.JTextField amount3;
    private javax.swing.JTextField amount4;
    private javax.swing.JTextField area;
    private javax.swing.JTextField date;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField finalamount;
    private javax.swing.JTextField flatno;
    private javax.swing.JTextField floorno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_sname;
    private javax.swing.JTextField mode;
    private javax.swing.JTextField month;
    private javax.swing.JTextField month1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField particulars1;
    private javax.swing.JTextField particulars2;
    private javax.swing.JTextField particulars3;
    private javax.swing.JTextField particulars4;
    private javax.swing.JTextField phoneno;
    private javax.swing.JTextField receipt;
    private javax.swing.JTextField search;
    private javax.swing.JTextField textamount;
    private javax.swing.JTextField trno;
    private javax.swing.JTextField year;
    private javax.swing.JTextField year1;
    private javax.swing.JTextField year2;
    // End of variables declaration//GEN-END:variables
}
