
import Project.MyConnection;
import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yugal
 */
public class Receipt extends javax.swing.JFrame {
    
    public String one_to_hund(int n){
        String str ="";
        while (n!=0){
            if(n==1){
                str= str+"One";
                n=0;
            }
            else if(n==2){
                str= str+"Two";
                n=0;
            }
            else if(n==3){
                str= str+"Three";
                n=0;
            }
            else if(n==4){
                str= str+"Four";
                n=0;
            }else if(n==5){
                str= str+"Five";
                n=0;
            }
            else if(n==6){
                str= str+"Six";
                n=0;
            }
            else if(n==7){
                str= str+"Seven";
                n=0;
            }
            else if(n==8){
                str= str+"Eight";
                n=0;
            }
            else if(n==9){
                str= str+"Nine";
                n=0;
            }
            else if(n==10){
                str= str+"Ten";
                n=0;
            }
             else if(n==11){
                str= str+"Eleven";
                n=0;
            }
             else if(n==12){
                str= str+"Twelve";
                n=0;
            }
             else if(n==13){
                str= str+"Thirteen";
                n=0;
            }
             else if(n==14){
                str= str+"Fourteen";
                n=0;
            }
             else if(n==15){
                str= str+"Ten";
                n=0;
            }
             else if(n==16){
                str= str+"Fiveteen";
                n=0;
            }
             else if(n==17){
                str= str+"Sixteen";
                n=0;
            }
             else if(n==18){
                str= str+"Seventeen";
                n=0;
            }
             else if(n==10){
                str= str+"Eighteen";
                n=0;
            }
             else if(n==19){
                str= str+"Nineteen";
                n=0;
            }
             else if(n>=20 && n<30){
                str= str+"Twenty";
                n=n-20;
            }
            else if(n>=30 && n<40){
                str= str+"Thirty";
                n=n-30;
            }
             else if(n>=40 && n<50){
                str= str+"Fourty";
                n=n-40;
            }
             else if(n>=50 && n<60){
                str= str+"Fifty";
                n=n-50;
            }
             else if(n>=60 && n<70){
                str= str+"Sixty";
                n=n-60;
            }
             else if(n>=70 && n<80){
                str= str+"Seventy";
                n=n-70;
            }
             else if(n>=80 && n<90){
                str= str+"Eighty";
                n=n-80;
            }
             else if(n>=90 && n<100){
                str= str+"Ninety";
                n=n-90;
            }
        }
        return str;
    }
    public String convert (int m){
        String str ="";
        while(m!=0){
            if(m>=1 && m<100){
                str = str+one_to_hund(m);
            }
            else if(m>=100 && m<1000){
                str = str+one_to_hund(m/100);
                str = str +"Hundred";
                m=m%100;
            }
            else if(m>=1000 && m<10000){
                str = str+one_to_hund(m/1000);
                str = str +"Thousand";
                m=m%1000;
            }
           
    }
    return str;
    }

    /**
     * Creates new form Receipt
     */
    public Receipt() {
        initComponents();
        jComboBox_Floor.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox_Floor = new javax.swing.JComboBox<>();
        jComboBox_Flat = new javax.swing.JComboBox<>();
        jTextField_Amount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox_Name = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RECEIPT PRINTING SYSTEM");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("YEAR:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("FLOOR NO. :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("FLAT NO. :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("AREA OF FLAT :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("RECEIVED FROM SHRI/SMT. :");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YYYY-YY", "2029-30", "2028-29", "2027-28", "2026-27", "2025-26", "2024-25", "2023-24", "2022-23", "2021-22", "2020-21", "2019-20", "2018-19", "2017-18", "2016-17", "2015-16", "2014-15", "2013-14", "2012-13", "2011-12", "2010-11", "2009-10", "2008-09", "2007-08", "2006-07", "2005-06", "2004-05", "2003-04", "2002-03", "2001-02        " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("DATE :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("PARTICULARS :");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEFAULT", "ENTRRANCE FEE", "SHARES", "DEPOSITE", "CONTRIBUTION TOWARDS CONSTRUCTION", "MUNICIPAL TAXES", "WATER CHARGES", "ELECTRICITY CHARGES", "PARKING CHARGES", "LIFT CHARGES", "SINKING FUND", "MAINTENANCE CHARGES", "INSURANCE", "NON-OCCUPING CHARGES", "DONATION FLAT TRANSFER CHARGES", "FINE/LATE FEE", "MISCELLANEOUS", "LAST YEAR BALANCE IN" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox_Floor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox_Floor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        jComboBox_Floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_FloorActionPerformed(evt);
            }
        });

        jComboBox_Flat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox_Flat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_FlatActionPerformed(evt);
            }
        });

        jTextField_Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AmountActionPerformed(evt);
            }
        });
        jTextField_Amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_AmountKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("AMOUNT :");

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YYYY-YY", "2029-30", "2028-29", "2027-28", "2026-27", "2025-26", "2024-25", "2023-24", "2022-23", "2021-22", "2020-21", "2019-20", "2018-19", "2017-18", "2016-17", "2015-16", "2014-15", "2013-14", "2012-13", "2011-12", "2010-11", "2009-10", "2008-09", "2007-08", "2006-07", "2005-06", "2004-05", "2003-04", "2002-03", "2001-02        " }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox_Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_NameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 231, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_Floor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_Flat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, 0, Short.MAX_VALUE)
                            .addComponent(jTextField_Amount)
                            .addComponent(jComboBox4, 0, 231, Short.MAX_VALUE)
                            .addComponent(jComboBox_Name, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jComboBox2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Floor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Flat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(276, 276, 276))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox_FloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_FloorActionPerformed
        // TODO add your handling code here:
        try{
        if(jComboBox_Floor.getSelectedItem().equals("1"))
        {
            jComboBox_Name.removeAllItems();
            jComboBox_Name.setSelectedItem(null);
            jComboBox_Flat.removeAllItems();
            jComboBox_Flat.setSelectedItem(null);
            jComboBox_Name.addItem("102-E Satish  Sukhdev Patil (Rental)");
            jComboBox_Name.addItem("103-E Kakade Satish Yashwant");
            jComboBox_Flat.addItem("102");
            jComboBox_Flat.addItem("103");
        }
         else if(jComboBox_Floor.getSelectedItem().equals("2"))
        {
            jComboBox_Name.removeAllItems();
            jComboBox_Name.setSelectedItem(null);
            jComboBox_Flat.removeAllItems();
            jComboBox_Flat.setSelectedItem(null);
            jComboBox_Flat.addItem("201");
            jComboBox_Flat.addItem("202");
            jComboBox_Flat.addItem("203");
            jComboBox_Flat.addItem("204");
            jComboBox_Name.addItem("201-E Deshpande Ashay");
            jComboBox_Name.addItem("202-E Katti Kaustubhmony S");
            jComboBox_Name.addItem("203-E Ajnadkar Atul Vishwanath");
            jComboBox_Name.addItem("204-E Parab Rajesh Shivram");
        }
         else if(jComboBox_Floor.getSelectedItem().equals("3"))
        {
            jComboBox_Name.removeAllItems();
            jComboBox_Name.setSelectedItem(null);
            jComboBox_Flat.removeAllItems();
            jComboBox_Flat.setSelectedItem(null);
            jComboBox_Flat.addItem("301");
            jComboBox_Flat.addItem("302");
            jComboBox_Flat.addItem("303");
            jComboBox_Flat.addItem("304");
            jComboBox_Name.addItem("301-E Pethkar Rahul Prakash");
            jComboBox_Name.addItem("302-E RAJU VENKATESAN MOHANRAJ");
            jComboBox_Name.addItem("303-E Khole Dhanjay Bhalchandra");
            jComboBox_Name.addItem("304-E Shrivastava Sangeet Kumar (Rental)");
            
        }
         else if(jComboBox_Floor.getSelectedItem().equals("4"))
        {
            jComboBox_Name.removeAllItems();
            jComboBox_Name.setSelectedItem(null);
            jComboBox_Flat.removeAllItems();
            jComboBox_Flat.setSelectedItem(null);
            jComboBox_Flat.addItem("401");
            jComboBox_Flat.addItem("402");
            jComboBox_Flat.addItem("403");
            jComboBox_Flat.addItem("404");
            jComboBox_Name.addItem("401-E Yadkikar Harshal Chandrashekhar");
            jComboBox_Name.addItem("402-E Devrajan Vijaykumar R");
            jComboBox_Name.addItem("403-E Khatavkar Uday Pandurang");
            jComboBox_Name.addItem("404-E Bamne Vivek Sakharam");
        }
         else if(jComboBox_Floor.getSelectedItem().equals("5"))
        {
            jComboBox_Name.removeAllItems();
            jComboBox_Name.setSelectedItem(null);
            jComboBox_Flat.removeAllItems();
            jComboBox_Flat.setSelectedItem(null);
            jComboBox_Flat.addItem("501");
            jComboBox_Flat.addItem("502");
            jComboBox_Flat.addItem("503");
            jComboBox_Flat.addItem("504");
            jComboBox_Name.addItem("501-E Sanas Ramesh Rajaram");
            jComboBox_Name.addItem("502-E Phapale  Dattatrat Baban (Rental)");
            jComboBox_Name.addItem("503-E Pande Abhay Mukund (Rental)");
            jComboBox_Name.addItem("504-E Gupta Mohanlal   G (Rental)");
        }
         else if(jComboBox_Floor.getSelectedItem().equals("6"))
        {
            jComboBox_Name.removeAllItems();
            jComboBox_Name.setSelectedItem(null);
            jComboBox_Flat.removeAllItems();
            jComboBox_Flat.setSelectedItem(null);
            jComboBox_Flat.addItem("601");
            jComboBox_Flat.addItem("602");
            jComboBox_Flat.addItem("603");
            jComboBox_Flat.addItem("604");
            jComboBox_Name.addItem("601-E Khare Ranjeet Krushnara");
            jComboBox_Name.addItem("602-E Om Hari Nishad (Rental)");
            jComboBox_Name.addItem("603-E Pawan Vijay Kale");
            jComboBox_Name.addItem("604-E Kulkarni Shrirang Ragvendra (Rental)");
        }
         else if(jComboBox_Floor.getSelectedItem().equals("7"))
        {
            jComboBox_Flat.removeAllItems();
            jComboBox_Name.removeAllItems();
            jComboBox_Name.setSelectedItem(null);
            jComboBox_Flat.setSelectedItem(null);
            jComboBox_Flat.addItem("701");
            jComboBox_Flat.addItem("702");
            jComboBox_Flat.addItem("703");
            jComboBox_Flat.addItem("704");
            jComboBox_Name.addItem("701-E Kulkarni Guruprasad S (Rental)");
            jComboBox_Name.addItem("702-E Bhorpe Ravindra Madhukar");
            jComboBox_Name.addItem("703-E Dolaskar Sudhir Mohan");
            jComboBox_Name.addItem("704-E Palaskar Pratik Eknath");
        }
      }catch (Exception e){
          System.out.println(e);
      }
        
    }//GEN-LAST:event_jComboBox_FloorActionPerformed

    private void jComboBox_FlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_FlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_FlatActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_NameActionPerformed

    private void jTextField_AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AmountActionPerformed

    private void jTextField_AmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AmountKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField_AmountKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox_Flat;
    private javax.swing.JComboBox<String> jComboBox_Floor;
    private javax.swing.JComboBox<String> jComboBox_Name;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_Amount;
    // End of variables declaration//GEN-END:variables

}   
